# Generated by Django 5.2.3 on 2025-06-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_recoverycode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporteddevice',
            name='home_io_room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='home_io_room',
        ),
        migrations.RemoveConstraint(
            model_name='supporteddevice',
            name='unique_addr_data_memtype',
        ),
        migrations.RemoveField(
            model_name='supporteddevice',
            name='address',
        ),
        migrations.RemoveField(
            model_name='supporteddevice',
            name='contact_type',
        ),
        migrations.RemoveField(
            model_name='supporteddevice',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='supporteddevice',
            name='memory_type',
        ),
        migrations.DeleteModel(
            name='HomeIORoom',
        ),
    ]
