from django.db import models
from django.utils import timezone
from .device_models import Device
from .home_models import Room, SmartHome


class DeviceLog1Min(models.Model):
    """
    Records the energy usage of a device at one-minute intervals.
    
    This gives us high-resolution data about device energy consumption,
    allowing us to create detailed usage reports and visualizations.
    We track both the status (on/off) and the actual energy used.
    """
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    status = models.BooleanField()
    energy_usage = models.FloatField()
    created_at = models.DateTimeField(default=timezone.now)


class DeviceLogDaily(models.Model):
    """
    Aggregated daily energy usage for a device.
    
    Instead of storing every minute's data forever, we aggregate it into
    daily summaries to save space while still providing useful historical data.
    
    The status_usage_details field can store additional information like
    how long the device was on vs. off during the day.
    """
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    date = models.DateField()
    total_energy_usage = models.FloatField(default=0.0)
    status_usage_details = models.JSONField(default=dict)  # For storing on/off intervals if needed


class DeviceLogMonthly(models.Model):
    """
    Aggregated monthly energy usage for a device.
    
    This provides an even higher level of aggregation for long-term
    analysis and reporting. Month and year are stored as separate fields
    to make querying by month or year more efficient.
    """
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    month = models.IntegerField()
    year = models.IntegerField()
    total_energy_usage = models.FloatField(default=0.0)
    daily_summaries = models.JSONField(default=dict)


class RoomLog1Min(models.Model):
    """
    Records the energy usage of an entire room at one-minute intervals.
    
    This aggregates the energy usage of all devices in a room, giving us
    a picture of which rooms are using the most energy at any given time.
    """
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    energy_usage = models.FloatField()
    created_at = models.DateTimeField(default=timezone.now)


class RoomLogDaily(models.Model):
    """
    Aggregated daily energy usage for a room.
    
    Similar to device logs, we aggregate room energy usage into daily
    summaries for easier analysis of room-level consumption patterns.
    """
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    date = models.DateField()
    total_energy_usage = models.FloatField(default=0.0)


class RoomLogMonthly(models.Model):
    """
    Aggregated monthly energy usage for a room.
    
    This provides a long-term view of which rooms use the most energy
    across different months of the year.
    """
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    month = models.IntegerField()
    year = models.IntegerField()
    total_energy_usage = models.FloatField(default=0.0)


class EnergyGeneration1Min(models.Model):
    """
    Records the energy generated by a smart home at one-minute intervals.
    
    This tracks how much energy the home's solar panels (or other generation sources)
    are producing, allowing us to compare generation against consumption.
    """
    home = models.ForeignKey(SmartHome, on_delete=models.CASCADE)
    energy_generation = models.FloatField()
    created_at = models.DateTimeField(default=timezone.now)


class EnergyGenerationDaily(models.Model):
    """
    Aggregated daily energy generation for a smart home.
    
    This gives us a day-by-day view of how much energy the home produced,
    which we can compare against the home's total consumption.
    """
    home = models.ForeignKey(SmartHome, on_delete=models.CASCADE)
    date = models.DateField()
    total_energy_generation = models.FloatField(default=0.0)


class EnergyGenerationMonthly(models.Model):
    """
    Aggregated monthly energy generation for a smart home.
    
    This provides a long-term view of the home's energy production patterns,
    useful for seasonal analysis (e.g., summer vs winter generation).
    """
    home = models.ForeignKey(SmartHome, on_delete=models.CASCADE)
    month = models.IntegerField()
    year = models.IntegerField()
    total_energy_generation = models.FloatField(default=0.0)
